# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb_dev_ex',
                'doc_host': 'https://hashd2035.github.io',
                'git_url': 'https://github.com/hashd2035/nb_dev_ex',
                'lib_path': 'nb_dev_ex'},
  'syms': {'nb_dev_ex.core': {'nb_dev_ex.core.foo': ('core.html#foo', 'nb_dev_ex/core.py')}}}
